#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
PREFIX geoes: <http://geo.marmotta.es/ontology#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT DISTINCT (geof:rcc8ntppi (?wkt,?wkt2) as ?rcc8ntppi) 
WHERE {  
  ?subject a <http://geo.marmotta.es/ontology#provincia>.
  ?subject rdfs:label "Madrid"@es.
  ?subject geoes:hasExactGeometry ?geo.
  ?geo geo:asWKT ?wkt.
  
  ?subject2 a <http://geo.marmotta.es/ontology#municipio>.
  ?subject2 rdfs:label ?labelMunicipios.
  ?subject2 geoes:hasExactGeometry ?geo2.
  ?geo2 geo:asWKT ?wkt2.
  
  FILTER (geof:rcc8ntppi (?wkt,?wkt2))      
}