ASK WHERE {
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml1/rdfa1.1/0054.xhtml> <http://purl.org/dc/elements/1.1/creator> "Fabien Gandon" .
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml1/rdfa1.1/0054.xhtml> <http://purl.org/dc/elements/1.1/publisher> "Fabien Gandon" .
}