#
#    Licensed to the Apache Software Foundation (ASF) under one or more
#    contributor license agreements.  See the NOTICE file distributed with
#    this work for additional information regarding copyright ownership.
#    The ASF licenses this file to You under the Apache License, Version 2.0
#    (the "License"); you may not use this file except in compliance with
#    the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

language: java

branches:
  only:
  - MARMOTTA-660 # Add just for migration testing purposes
  - master
  - develop

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.4"

jdk:
- oraclejdk7
- oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_install:
- echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

- mysql -u root -e 'CREATE DATABASE kiwitest;'
- mysql -u root -e "CREATE USER 'kiwi'@'localhost' IDENTIFIED BY 'kiwi';"
- mysql -u root -e "GRANT ALL ON kiwitest.* TO 'kiwi'@'localhost';"

- psql -c 'create database kiwitest;' -U postgres
- psql -c "CREATE USER kiwi WITH PASSWORD 'kiwi';" -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE kiwitest to kiwi;' -U postgres

install: true

script: mvn clean install
