PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbp: <http://dbpedia.org/ontology/>
ASK {
    <http://dbpedia.org/resource/Berlin> rdfs:label "Berlin"@en .
    <http://dbpedia.org/resource/Berlin> rdf:type dbp:City
}
