PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gn: <http://www.geonames.org/ontology#>
ASK {
    <http://sws.geonames.org/3020251/> gn:name "Embrun" .
    <http://sws.geonames.org/3020251/> rdf:type gn:Feature
}
