PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
ASK {
    http://rdfohloh.wikier.org/project/marmotta> doap:name "Apache Marmotta (incubator)" .
    <http://rdfohloh.wikier.org/project/marmotta> rdf:type doap:Project
}
