PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?p1 ?fn ?p2 ?age WHERE {
    ?p1 foaf:name ?fn .
    OPTIONAL { ?p1 foaf:knows ?p2 . ?p2 foaf:age ?age }
}