/**
 * Copyright (C) 2013 Salzburg Research.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * This class is generated by jOOQ
 */
package org.apache.marmotta.platform.sparql.model;

import org.apache.marmotta.platform.sparql.model.tables.TNodes;
import org.apache.marmotta.platform.sparql.model.tables.TTriples;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table public.kiwinode
	 */
	public static TNodes KIWINODE = TNodes.KIWINODE;

	/**
	 * The table public.triples
	 */
	public static TTriples TRIPLES = TTriples.TRIPLES;

	/**
	 * No instances
	 */
	private Tables() {}
}
