PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
ASK {
    <http://graph.facebook.com/160617097307237> dct:title "The Hobbit"@en ;
                                          rdf:type schema:Movie ;
                                          schema:genre "Fantasy Adventure" .
}
