/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * This class is generated by jOOQ
 */
package org.apache.marmotta.platform.sparql.model.tables.records;

import org.apache.marmotta.platform.sparql.model.tables.TTriples;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class RTriples extends org.jooq.impl.TableRecordImpl<RTriples> {

	private static final long serialVersionUID = 971957447;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Long value) {
		setValue(TTriples.TRIPLES.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Long getId() {
		return getValue(TTriples.TRIPLES.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(TTriples.TRIPLES.CREATED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreated() {
		return getValue(TTriples.TRIPLES.CREATED);
	}

	/**
	 * An uncommented item
	 */
	public void setDeleted(java.lang.Boolean value) {
		setValue(TTriples.TRIPLES.DELETED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getDeleted() {
		return getValue(TTriples.TRIPLES.DELETED);
	}

	/**
	 * An uncommented item
	 */
	public void setDeletedat(java.sql.Timestamp value) {
		setValue(TTriples.TRIPLES.DELETEDAT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getDeletedat() {
		return getValue(TTriples.TRIPLES.DELETEDAT);
	}

	/**
	 * An uncommented item
	 */
	public void setInferred(java.lang.Boolean value) {
		setValue(TTriples.TRIPLES.INFERRED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getInferred() {
		return getValue(TTriples.TRIPLES.INFERRED);
	}

	/**
	 * An uncommented item
	 */
	public void setVersion(java.lang.Long value) {
		setValue(TTriples.TRIPLES.VERSION, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getVersion() {
		return getValue(TTriples.TRIPLES.VERSION);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb552fbdfe5
	 * FOREIGN KEY (context_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public void setContextId(java.lang.Long value) {
		setValue(TTriples.TRIPLES.CONTEXT_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb552fbdfe5
	 * FOREIGN KEY (context_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public java.lang.Long getContextId() {
		return getValue(TTriples.TRIPLES.CONTEXT_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb536cf857c
	 * FOREIGN KEY (creator_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public void setCreatorId(java.lang.Long value) {
		setValue(TTriples.TRIPLES.CREATOR_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb536cf857c
	 * FOREIGN KEY (creator_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public java.lang.Long getCreatorId() {
		return getValue(TTriples.TRIPLES.CREATOR_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb5d2e5bf7d
	 * FOREIGN KEY (object_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public void setObjectId(java.lang.Long value) {
		setValue(TTriples.TRIPLES.OBJECT_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb5d2e5bf7d
	 * FOREIGN KEY (object_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public java.lang.Long getObjectId() {
		return getValue(TTriples.TRIPLES.OBJECT_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb593957dff
	 * FOREIGN KEY (property_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public void setPropertyId(java.lang.Long value) {
		setValue(TTriples.TRIPLES.PROPERTY_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb593957dff
	 * FOREIGN KEY (property_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public java.lang.Long getPropertyId() {
		return getValue(TTriples.TRIPLES.PROPERTY_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb5c267907c
	 * FOREIGN KEY (subject_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public void setSubjectId(java.lang.Long value) {
		setValue(TTriples.TRIPLES.SUBJECT_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT triples__fkeba30bb5c267907c
	 * FOREIGN KEY (subject_id)
	 * REFERENCES public.kiwinode (id)
	 * </pre></code>
	 */
	public java.lang.Long getSubjectId() {
		return getValue(TTriples.TRIPLES.SUBJECT_ID);
	}

	/**
	 * Create a detached TriplesRecord
	 */
	public RTriples() {
		super(TTriples.TRIPLES);
	}
}
