ASK WHERE {
	<http://www.blogger.com/profile/1109404> <http://xmlns.com/foaf/0.1/img> <http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml1/rdfa1.1/photo1.jpg> .
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml1/rdfa1.1/photo1.jpg> <http://purl.org/dc/elements/1.1/title> "Portrait of Mark" .
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml1/rdfa1.1/photo1.jpg> <http://purl.org/dc/elements/1.1/creator> <http://www.blogger.com/profile/1109404> .
}