ASK WHERE {
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml1/rdfa1.1/0015.xhtml> <http://purl.org/dc/elements/1.1/creator> "Fyodor Dostoevsky" .
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/xhtml1/rdfa1.1/0015.xhtml> <http://purl.org/dc/elements/1.1/source> <urn:isbn:0140449132> .
}