PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX sioc-types: <http://rdfs.org/sioc/types#>
ASK {
    <http://en.wikipedia.org/wiki/Marmot> dct:title "Marmot" ;
                                          rdf:type sioc-types:WikiArticle ;
                                          sioc:topic <http://en.wikipedia.org/wiki/Category:Ground_squirrels> .
}
